### ISSUE TITLE
Is there an api/programmatic way to update TaskPane cache?

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/Office-Addin-TaskPane-React-JS#32]
HI, I found that TaskPane Add in cache is inside 
C:\Users\USERNAME\AppData\Local\Microsoft\Office\16.0\Wef\AppCommands, I can only update it by clicking at my addin tab(take excel for example) and select the addin then click 'add'.

Is there an api/programmatic way to update the cache? I tried with Marco but seems it can only deal with the automation add-ins instead of the web add-in

**Comment by millerds** [comment]
Update your version number to invalidate the cache.  Feel free to re-open with more information if you have more questions.
