### ISSUE TITLE
SecurityError with websockets

### ISSUE THREAD

**Issue by tytech3** [OfficeDev/Office-Addin-TaskPane-React-JS#39]
I'm getting a very ambiguous error when trying to connect to my websocket server

`Error: SecurityError` 

I've searched multiple places - stackoverflow has tons of office-js questions and 0 answers. Can anyone point me in the right direction to sovle this issue? Can i just disable security and bypass this?

**Comment by kbrandl** [comment]
Closing as duplicate of https://github.com/OfficeDev/office-js/issues/1018. 

@tytech3 sorry to hear you're having trouble. FYI, the Office JS team monitors all related repos, so you just need to open an issue once, in a single repo. For product-related questions/issues like this, **OfficeDev/office-js** is the best place to open the issue, so I'll leave your issue open there (and close duplicate issues elsewhere, like here). Thanks!
