### ISSUE TITLE
Looking for instructions on how to dockerize the app

### ISSUE THREAD

**Issue by rdalbuquerque** [OfficeDev/Office-Addin-TaskPane-React-JS#60]
Hi,

I have been trying to dockerize the app without much success. Since I don't have much experience on ReactJS webpack apps I was hoping you would have some instructions on how to do it for this project in particular.

Thanks in advance.

**Comment by millerds** [comment]
I don't think there is anything unique to the template that would affect dockerization.  There seems to be lots of information on the web about how to dockerize reactjs (I have not tried anything myself): https://www.bing.com/search?q=dockerize+reactjs

If you run into any problems specific to office add-ins please post those.
