### ISSUE TITLE
i want to open automatically this Add-in when open word document how i can ? Extra attention is needed

### ISSUE THREAD

**Issue by hammadshahid-170** [OfficeDev/Office-Addin-TaskPane-React-JS#65]
i want to open automatically this Add-in when open word document how i can ?

**Comment by igor-ribeiiro** [comment]
Try this documentation: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

If you still have trouble please re-open.
