### ISSUE TITLE
Unable to web inspector on Mac Excel add-in

### ISSUE THREAD

**Issue by solancer** [OfficeDev/Office-Addin-TaskPane-React-JS#81]
Setting below value in the terminal as per the [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)

`defaults write com.microsoft.Excel OfficeWebAddinDeveloperExtras -bool true`

However, I don't see inspect option upon right-clicking in the task pane

**Comment by millerds** [comment]
What version of office do you have installed?

**Comment by solancer** [comment]
@millerds 

<img width="374" alt="Screenshot 2022-06-24 at 2 18 08 pm" src="https://user-images.githubusercontent.com/800668/175499582-3830083f-b308-492b-b11c-439696daf290.png">

**Comment by millerds** [comment]
How did you install office on your machine?

**Comment by solancer** [comment]
through office 365 post login

![Screenshot 2022-06-28 at 3 29 15 pm](https://user-images.githubusercontent.com/800668/176151950-a90c4a67-5ad9-46d4-95af-4952b6d962f8.png)

**Comment by millerds** [comment]
Sorry for disappearing for a while . . . are you still having problems?
