### ISSUE TITLE
How to set format for Range cell

### ISSUE THREAD

**Issue by LiuXiao617111** [OfficeDev/Office-Addin-TaskPane-React-JS#82]
How can l set the format like the screenshot.

![image](https://user-images.githubusercontent.com/8858358/170168339-be5f4023-d200-47cb-bbbe-46545dba0a40.png)

**Comment by LiuXiao617111** [comment]
by JS API

**Comment by millerds** [comment]
see: https://github.com/OfficeDev/Office-Addin-Scripts/issues/642
