### ISSUE TITLE
Missing hint in documentation? Is this example only working with a outlook-emailadresse?

### ISSUE THREAD

**Issue by ffischer1984** [OfficeDev/Office-Addin-TaskPane-React-JS#92]
according to [here](https://answers.microsoft.com/en-us/outlook_com/forum/all/get-add-ins-for-outlook-2019-is-disabled/5d319896-700b-4b1c-9afc-a75ad3c79090). The "Get Add-In"-Button is only displayed when outlook is connected to a outlook-emailadress. Is this correct? If yes, there should be a big disclaimer on the documentation page & the github-readme page that it only works with an MS emailadress to save others the time.

**Comment by millerds** [comment]
This repo is for building add-in for any of the Office application not just Outlook.  Word, Excel, and PowerPoint don't have the requirement for an account and so a disclaimer wouldn't make sense.
